-- MySQL Script generated by MySQL Workbench
-- Fri Dec  4 16:20:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fz_webapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fz_webapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fz_webapp` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `fz_webapp` ;

-- -----------------------------------------------------
-- Table `fz_webapp`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fz_webapp`.`customer` (
  `custid` VARCHAR(50) NOT NULL,
  `passwd` VARCHAR(40) NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  `address` VARCHAR(50) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `level` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`custid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fz_webapp`.`bottle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fz_webapp`.`bottle` (
  `custid` VARCHAR(50) NOT NULL,
  `soju` INT NULL DEFAULT NULL,
  `beer` INT NULL DEFAULT NULL,
  `milk` INT NULL DEFAULT NULL,
  `water` INT NULL DEFAULT NULL,
  `point` INT NULL DEFAULT NULL,
  PRIMARY KEY (`custid`),
  CONSTRAINT `bottle_ibfk_1`
    FOREIGN KEY (`custid`)
    REFERENCES `fz_webapp`.`customer` (`custid`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fz_webapp`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fz_webapp`.`cart` (
  `cartid` INT NOT NULL,
  `customer_custid` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cartid`),
  INDEX `fk_cart_customer1_idx` (`customer_custid` ASC) VISIBLE,
  CONSTRAINT `fk_cart_customer1`
    FOREIGN KEY (`customer_custid`)
    REFERENCES `fz_webapp`.`customer` (`custid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fz_webapp`.`offline_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fz_webapp`.`offline_order` (
  `orderid` INT NOT NULL,
  `custid` VARCHAR(50) NULL DEFAULT NULL,
  `allprice` INT NULL DEFAULT NULL,
  `orderdate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`orderid`),
  INDEX `offline_order_ibfk_1` (`custid` ASC) INVISIBLE,
  INDEX `offline_order_ibfk_2` (`allprice` ASC) VISIBLE,
  CONSTRAINT `offline_order_ibfk_1`
    FOREIGN KEY (`custid`)
    REFERENCES `fz_webapp`.`customer` (`custid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fz_webapp`.`offline_store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fz_webapp`.`offline_store` (
  `storeid` INT NOT NULL,
  `storename` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`storeid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fz_webapp`.`offline_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fz_webapp`.`offline_product` (
  `offlineproduct_id` INT NOT NULL AUTO_INCREMENT,
  `storeid` INT NULL DEFAULT NULL,
  `offlineproduct_name` VARCHAR(45) NULL DEFAULT NULL,
  `offlineproduct_num` INT NULL DEFAULT NULL,
  `offlineproduct_price` INT NULL DEFAULT NULL,
  PRIMARY KEY (`offlineproduct_id`),
  INDEX `storeid_idx` (`storeid` ASC) VISIBLE,
  CONSTRAINT `storeid`
    FOREIGN KEY (`storeid`)
    REFERENCES `fz_webapp`.`offline_store` (`storeid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 607
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fz_webapp`.`online_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fz_webapp`.`online_order` (
  `orderid` INT NOT NULL,
  `customer_custid` VARCHAR(50) NOT NULL,
  `allprice` INT NULL DEFAULT NULL,
  `orderdate` INT NULL DEFAULT NULL,
  PRIMARY KEY (`orderid`),
  INDEX `fk_online_order_customer1_idx` (`customer_custid` ASC) VISIBLE,
  CONSTRAINT `fk_online_order_customer1`
    FOREIGN KEY (`customer_custid`)
    REFERENCES `fz_webapp`.`customer` (`custid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fz_webapp`.`online_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fz_webapp`.`online_product` (
  `productid` INT NOT NULL,
  `productname` VARCHAR(45) NOT NULL,
  `brand` VARCHAR(45) NULL DEFAULT NULL,
  `price` INT NOT NULL,
  `big_category` VARCHAR(45) NULL DEFAULT NULL,
  `small_category` VARCHAR(45) NULL DEFAULT NULL,
  `img` INT NOT NULL,
  PRIMARY KEY (`productid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fz_webapp`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fz_webapp`.`order_items` (
  `orderid` INT NOT NULL,
  `productid` INT NOT NULL,
  `custid` VARCHAR(45) NOT NULL,
  `count` INT NOT NULL,
  PRIMARY KEY (`orderid`),
  INDEX `fk_order_items_online_order1_idx` (`orderid` ASC) VISIBLE,
  CONSTRAINT `fk_order_items_online_order1`
    FOREIGN KEY (`orderid`)
    REFERENCES `fz_webapp`.`online_order` (`orderid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fz_webapp`.`level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fz_webapp`.`level` (
  `customer_custid` VARCHAR(50) NOT NULL,
  `level` VARCHAR(45) NOT NULL,
  INDEX `fk_level_customer1_idx` (`customer_custid` ASC) VISIBLE,
  CONSTRAINT `fk_level_customer1`
    FOREIGN KEY (`customer_custid`)
    REFERENCES `fz_webapp`.`customer` (`custid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fz_webapp`.`notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fz_webapp`.`notice` (
  `board_id` INT NOT NULL,
  `custid` VARCHAR(50) NOT NULL,
  `board_title` VARCHAR(100) NULL,
  `board_contant` VARCHAR(1000) NULL,
  `board_date` DATE NULL,
  INDEX `fk_notice_customer1_idx` (`custid` ASC) VISIBLE,
  PRIMARY KEY (`board_id`),
  CONSTRAINT `fk_notice_customer1`
    FOREIGN KEY (`custid`)
    REFERENCES `fz_webapp`.`customer` (`custid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fz_webapp`.`qna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fz_webapp`.`qna` (
  `board_id` INT NOT NULL,
  `custid` VARCHAR(50) NOT NULL,
  `board_title` VARCHAR(100) NULL,
  `board_contant` VARCHAR(1000) NULL,
  `board_date` DATE NULL,
  INDEX `fk_qna_customer1_idx` (`custid` ASC) VISIBLE,
  UNIQUE INDEX `customer_custid_UNIQUE` (`custid` ASC) VISIBLE,
  PRIMARY KEY (`board_id`),
  CONSTRAINT `fk_qna_customer1`
    FOREIGN KEY (`custid`)
    REFERENCES `fz_webapp`.`customer` (`custid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fz_webapp`.`faq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fz_webapp`.`faq` (
  `board_id` INT NOT NULL,
  `custid` VARCHAR(50) NOT NULL,
  `board_title` VARCHAR(100) NOT NULL,
  `board_contant` VARCHAR(1000) NOT NULL,
  `board_date` DATE NOT NULL,
  PRIMARY KEY (`board_id`),
  INDEX `fk_faq_customer1_idx` (`custid` ASC) VISIBLE,
  CONSTRAINT `fk_faq_customer1`
    FOREIGN KEY (`custid`)
    REFERENCES `fz_webapp`.`customer` (`custid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
