alter table online_product add img int not null;

UPDATE `fz_webapp`.`online_product` SET `img` = '1' WHERE (`productid` = '18') and (`productname` = '크라프트 무지 만년 위클리\n') and (`price` = '2000');
UPDATE `fz_webapp`.`online_product` SET `img` = '2' WHERE (`productid` = '26') and (`productname` = 'A5 크라프트 무지노트\n') and (`price` = '2000');
UPDATE `fz_webapp`.`online_product` SET `img` = '3' WHERE (`productid` = '39') and (`productname` = '사이잘 빨대 세척솔\n') and (`price` = '2000');
UPDATE `fz_webapp`.`online_product` SET `img` = '4' WHERE (`productid` = '5') and (`productname` = '유기농 메쉬 파우치(S)\n') and (`price` = '3000');
UPDATE `fz_webapp`.`online_product` SET `img` = '5' WHERE (`productid` = '9') and (`productname` = '광목 빨대 주머니\n') and (`price` = '3000');
UPDATE `fz_webapp`.`online_product` SET `img` = '6' WHERE (`productid` = '28') and (`productname` = '스테인리스 빨대(일자형)\n') and (`price` = '3000');
UPDATE `fz_webapp`.`online_product` SET `img` = '7' WHERE (`productid` = '43') and (`productname` = '스테인리스 빨대(ㄱ자형)\n') and (`price` = '3500');
UPDATE `fz_webapp`.`online_product` SET `img` = '8' WHERE (`productid` = '2') and (`productname` = '스텐 고리집게(5p.)\n') and (`price` = '4000');
UPDATE `fz_webapp`.`online_product` SET `img` = '9' WHERE (`productid` = '7') and (`productname` = '스텐 미니집게(10pcs.)\n') and (`price` = '4000');
UPDATE `fz_webapp`.`online_product` SET `img` = '10' WHERE (`productid` = '8') and (`productname` = '유기농 메쉬 프로듀스백(S/M/L)\n') and (`price` = '4000');
UPDATE `fz_webapp`.`online_product` SET `img` = '11' WHERE (`productid` = '14') and (`productname` = '유기농면 프로듀스백(S/M/L)\n') and (`price` = '4500');
UPDATE `fz_webapp`.`online_product` SET `img` = '12' WHERE (`productid` = '37') and (`productname` = 'SCHOTT 쇼트 유리빨대(단품/세트)\n') and (`price` = '5000');
UPDATE `fz_webapp`.`online_product` SET `img` = '13' WHERE (`productid` = '45') and (`productname` = '다회용 밀랍 푸드백(S/L)\n') and (`price` = '5000');
UPDATE `fz_webapp`.`online_product` SET `img` = '14' WHERE (`productid` = '34') and (`productname` = '소창 프로듀스백(M)\n') and (`price` = '5500');
UPDATE `fz_webapp`.`online_product` SET `img` = '15' WHERE (`productid` = '20') and (`productname` = '소락 유기농 튤립백(도시락가방)\n') and (`price` = '6000');
UPDATE `fz_webapp`.`online_product` SET `img` = '16' WHERE (`productid` = '29') and (`productname` = '프로듀스백 (M)\n') and (`price` = '6000');
UPDATE `fz_webapp`.`online_product` SET `img` = '17' WHERE (`productid` = '25') and (`productname` = '에코백\n') and (`price` = '8000');
UPDATE `fz_webapp`.`online_product` SET `img` = '18' WHERE (`productid` = '32') and (`productname` = '유기농 스트링 에코백\n') and (`price` = '10000');
UPDATE `fz_webapp`.`online_product` SET `img` = '19' WHERE (`productid` = '22') and (`productname` = '유기농 하프메쉬 에코백\n') and (`price` = '12000');
UPDATE `fz_webapp`.`online_product` SET `img` = '20' WHERE (`productid` = '21') and (`productname` = '[도서] 지구생활안내서 바질[BASIL]\n') and (`price` = '13000');
UPDATE `fz_webapp`.`online_product` SET `img` = '21' WHERE (`productid` = '24') and (`productname` = '재활용 페트병 마켓백\n') and (`price` = '13000');
UPDATE `fz_webapp`.`online_product` SET `img` = '22' WHERE (`productid` = '30') and (`productname` = '재활용면 텀블러 가방\n') and (`price` = '13000');
UPDATE `fz_webapp`.`online_product` SET `img` = '23' WHERE (`productid` = '31') and (`productname` = '[도서] 매거진쓸[SSSSL]\n') and (`price` = '13000');
UPDATE `fz_webapp`.`online_product` SET `img` = '24' WHERE (`productid` = '11') and (`productname` = '[도서] 오늘을 조금 바꿉니다\n') and (`price` = '13410');
UPDATE `fz_webapp`.`online_product` SET `img` = '25' WHERE (`productid` = '23') and (`productname` = '[도서] 그건 쓰레기가 아니라고요\n') and (`price` = '14400');
UPDATE `fz_webapp`.`online_product` SET `img` = '26' WHERE (`productid` = '13') and (`productname` = '[도서] 채식연습\n') and (`price` = '15120');
UPDATE `fz_webapp`.`online_product` SET `img` = '27' WHERE (`productid` = '110') and (`productname` = '내열 유리빨대 일반용 8mm\n') and (`price` = '1500');
UPDATE `fz_webapp`.`online_product` SET `img` = '28' WHERE (`productid` = '109') and (`productname` = '내열 유리빨대 스무디용 12mm\n') and (`price` = '2000');
UPDATE `fz_webapp`.`online_product` SET `img` = '29' WHERE (`productid` = '107') and (`productname` = '친환경 제로웨이스트 내열 유리빨대 4종 세트\n') and (`price` = '6600');
UPDATE `fz_webapp`.`online_product` SET `img` = '30' WHERE (`productid` = '108') and (`productname` = '유리빨대 파우치 세트\n') and (`price` = '9900');
UPDATE `fz_webapp`.`online_product` SET `img` = '31' WHERE (`productid` = '115') and (`productname` = '[E,art] 친환경 스테인리스 빨대') and (`price` = '500');
UPDATE `fz_webapp`.`online_product` SET `img` = '32' WHERE (`productid` = '116') and (`productname` = '[e,art] 스텐 훅 집게') and (`price` = '500');
UPDATE `fz_webapp`.`online_product` SET `img` = '33' WHERE (`productid` = '121') and (`productname` = 'E,art 친환경 대나무 빨대') and (`price` = '1300');
UPDATE `fz_webapp`.`online_product` SET `img` = '34' WHERE (`productid` = '119') and (`productname` = '[E,art] 광목 주머니') and (`price` = '1800');
UPDATE `fz_webapp`.`online_product` SET `img` = '35' WHERE (`productid` = '118') and (`productname` = '[E,art] 프리미엄 강화 소창 원단 2겹 3겹') and (`price` = '2900');
UPDATE `fz_webapp`.`online_product` SET `img` = '36' WHERE (`productid` = '127') and (`productname` = '제로웨이스트 네트백') and (`price` = '4000');
UPDATE `fz_webapp`.`online_product` SET `img` = '37' WHERE (`productid` = '126') and (`productname` = 'E,art 포켓 장바구니') and (`price` = '17800');
UPDATE `fz_webapp`.`online_product` SET `img` = '38' WHERE (`productid` = '79') and (`productname` = '칫솔 파우치\n') and (`price` = '3500');
UPDATE `fz_webapp`.`online_product` SET `img` = '39' WHERE (`productid` = '93') and (`productname` = '프로듀스백\n') and (`price` = '4000');
UPDATE `fz_webapp`.`online_product` SET `img` = '40' WHERE (`productid` = '92') and (`productname` = '메쉬백\n') and (`price` = '8000');
UPDATE `fz_webapp`.`online_product` SET `img` = '41' WHERE (`productid` = '99') and (`productname` = '[바잇미] 미니에코백\n') and (`price` = '8900');
UPDATE `fz_webapp`.`online_product` SET `img` = '42' WHERE (`productid` = '102') and (`productname` = '[바잇미] 데일리 산책가방\n') and (`price` = '30900');
UPDATE `fz_webapp`.`online_product` SET `img` = '43' WHERE (`productid` = '104') and (`productname` = '[루디아의베틀] 루디아백\n') and (`price` = '40000');
UPDATE `fz_webapp`.`online_product` SET `img` = '44' WHERE (`productid` = '98') and (`productname` = '[루디아의베틀] 미니크로스백\n') and (`price` = '45600');
UPDATE `fz_webapp`.`online_product` SET `img` = '45' WHERE (`productid` = '105') and (`productname` = '[루디아의베틀] 코스타백\n') and (`price` = '74600');

UPDATE `fz_webapp`.`online_product` SET `img` = '1' WHERE (`productid` = '3') and (`productname` = '소창 2겹 행주 (손수건 대용)\n') and (`price` = '4000');
UPDATE `fz_webapp`.`online_product` SET `img` = '2' WHERE (`productid` = '17') and (`productname` = '네츄럴 린넨 손수건\n') and (`price` = '4000');
UPDATE `fz_webapp`.`online_product` SET `img` = '3' WHERE (`productid` = '51') and (`productname` = '천연 목욕수세미(어린수세미)\n') and (`price` = '4000');
UPDATE `fz_webapp`.`online_product` SET `img` = '4' WHERE (`productid` = '52') and (`productname` = '천연 비누주머니\n') and (`price` = '5000');
UPDATE `fz_webapp`.`online_product` SET `img` = '5' WHERE (`productid` = '47') and (`productname` = '친환경 대나무 칫솔\n') and (`price` = '5500');
UPDATE `fz_webapp`.`online_product` SET `img` = '6' WHERE (`productid` = '46') and (`productname` = '생분해 천연 치실/리필\n') and (`price` = '7000');
UPDATE `fz_webapp`.`online_product` SET `img` = '7' WHERE (`productid` = '50') and (`productname` = '스테인리스 혀클리너\n') and (`price` = '7000');
UPDATE `fz_webapp`.`online_product` SET `img` = '8' WHERE (`productid` = '54') and (`productname` = '소창 2겹 세안수건\n') and (`price` = '7000');
UPDATE `fz_webapp`.`online_product` SET `img` = '9' WHERE (`productid` = '41') and (`productname` = '소창 3겹 핸드타월\n') and (`price` = '8000');
UPDATE `fz_webapp`.`online_product` SET `img` = '10' WHERE (`productid` = '53') and (`productname` = '유기농 온몸비누 제주\n') and (`price` = '8000');
UPDATE `fz_webapp`.`online_product` SET `img` = '11' WHERE (`productid` = '55') and (`productname` = '천연 수세미 목욕장갑\n') and (`price` = '10000');
UPDATE `fz_webapp`.`online_product` SET `img` = '12' WHERE (`productid` = '6') and (`productname` = '휴대용 소창와입스(4매입)\n') and (`price` = '11000');
UPDATE `fz_webapp`.`online_product` SET `img` = '13' WHERE (`productid` = '48') and (`productname` = '유기농 햄프코튼 재사용 화장솜\n') and (`price` = '12000');
UPDATE `fz_webapp`.`online_product` SET `img` = '14' WHERE (`productid` = '56') and (`productname` = '플랑드비 올라이트 바디솝\n') and (`price` = '17000');
UPDATE `fz_webapp`.`online_product` SET `img` = '15' WHERE (`productid` = '57') and (`productname` = '재사용 화장지(10매입)\n') and (`price` = '25000');
UPDATE `fz_webapp`.`online_product` SET `img` = '16' WHERE (`productid` = '111') and (`productname` = '친환경 제로웨이스트 미세모 대나무 칫솔\n') and (`price` = '980');
UPDATE `fz_webapp`.`online_product` SET `img` = '17' WHERE (`productid` = '132') and (`productname` = '[E,art] 제로웨이스트 대나무 칫솔') and (`price` = '1250');
UPDATE `fz_webapp`.`online_product` SET `img` = '18' WHERE (`productid` = '114') and (`productname` = '[E,art] 프리미엄 강화 소창 와입스') and (`price` = '1350');
UPDATE `fz_webapp`.`online_product` SET `img` = '19' WHERE (`productid` = '136') and (`productname` = '규조토 비누 받침 심플 사각 트레이 1개') and (`price` = '2000');
UPDATE `fz_webapp`.`online_product` SET `img` = '20' WHERE (`productid` = '113') and (`productname` = '[e,art] 먼지없는 강화 소창 2겹 행주 (면100%)') and (`price` = '2100');
UPDATE `fz_webapp`.`online_product` SET `img` = '21' WHERE (`productid` = '130') and (`productname` = '과탄산소다 1kg 소창행주 정련 세제') and (`price` = '3900');
UPDATE `fz_webapp`.`online_product` SET `img` = '22' WHERE (`productid` = '138') and (`productname` = '저자극 바질 클렌징 비누') and (`price` = '5000');
UPDATE `fz_webapp`.`online_product` SET `img` = '23' WHERE (`productid` = '137') and (`productname` = '[e,art] 먼지없는 강화 소창 3겹 수건 (면100%)') and (`price` = '5200');
UPDATE `fz_webapp`.`online_product` SET `img` = '24' WHERE (`productid` = '133') and (`productname` = '저자극 오이가지 바디 비누') and (`price` = '6000');
UPDATE `fz_webapp`.`online_product` SET `img` = '25' WHERE (`productid` = '134') and (`productname` = '[E,art] 프리미엄 소창 목욕수건') and (`price` = '8300');
UPDATE `fz_webapp`.`online_product` SET `img` = '26' WHERE (`productid` = '135') and (`productname` = '[E,art] 삼베 샤워타월') and (`price` = '8300');
UPDATE `fz_webapp`.`online_product` SET `img` = '27' WHERE (`productid` = '139') and (`productname` = '[e,art] 재사용 화장솜') and (`price` = '8990');
UPDATE `fz_webapp`.`online_product` SET `img` = '28' WHERE (`productid` = '89') and (`productname` = '면비누망\n') and (`price` = '2500');
UPDATE `fz_webapp`.`online_product` SET `img` = '29' WHERE (`productid` = '76') and (`productname` = '대나무칫솔(성인/어린이용)\n') and (`price` = '3500');
UPDATE `fz_webapp`.`online_product` SET `img` = '30' WHERE (`productid` = '88') and (`productname` = '스테인레스 칫솔걸이\n') and (`price` = '4000');
UPDATE `fz_webapp`.`online_product` SET `img` = '31' WHERE (`productid` = '75') and (`productname` = '고체치약\n') and (`price` = '5900');
UPDATE `fz_webapp`.`online_product` SET `img` = '32' WHERE (`productid` = '62') and (`productname` = '[예고은] 삼베행주\n') and (`price` = '7900');
UPDATE `fz_webapp`.`online_product` SET `img` = '33' WHERE (`productid` = '77') and (`productname` = '[소락] 면화장솜 4pcs\n') and (`price` = '10000');
UPDATE `fz_webapp`.`online_product` SET `img` = '34' WHERE (`productid` = '91') and (`productname` = '[소락] 휴대용 와입스(4매입)\n') and (`price` = '11000');
UPDATE `fz_webapp`.`online_product` SET `img` = '35' WHERE (`productid` = '78') and (`productname` = '[예고은] 삼베샤워타월\n') and (`price` = '11900');
UPDATE `fz_webapp`.`online_product` SET `img` = '36' WHERE (`productid` = '81') and (`productname` = '유기농 핸드타월 (3매)\n') and (`price` = '12000');
UPDATE `fz_webapp`.`online_product` SET `img` = '37' WHERE (`productid` = '80') and (`productname` = '[더비건글로우] 오리지널 샴푸바\n') and (`price` = '15000');
UPDATE `fz_webapp`.`online_product` SET `img` = '38' WHERE (`productid` = '83') and (`productname` = '[솝퓨리]네버드라이 페이셜바\n') and (`price` = '15000');
UPDATE `fz_webapp`.`online_product` SET `img` = '39' WHERE (`productid` = '87') and (`productname` = '[솝퓨리]노세범 샴푸바(지성용)\n') and (`price` = '16000');
UPDATE `fz_webapp`.`online_product` SET `img` = '40' WHERE (`productid` = '82') and (`productname` = '[솝퓨리]안티로쓰 샴푸바(탈모방지)\n') and (`price` = '18000');
UPDATE `fz_webapp`.`online_product` SET `img` = '41' WHERE (`productid` = '85') and (`productname` = '[솝퓨리]리치리치 샴푸바(건성용)\n') and (`price` = '18000');
UPDATE `fz_webapp`.`online_product` SET `img` = '42' WHERE (`productid` = '84') and (`productname` = '유기농 수건 (3매)\n') and (`price` = '19500');
UPDATE `fz_webapp`.`online_product` SET `img` = '43' WHERE (`productid` = '86') and (`productname` = '[솝퓨리]오오클렌징바(여성청결제)\n') and (`price` = '24000');


UPDATE `fz_webapp`.`online_product` SET `img` = '1' WHERE (`productid` = '15') and (`productname` = '그랩 리페어 밀랍블록\n') and (`price` = '1500');
UPDATE `fz_webapp`.`online_product` SET `img` = '2' WHERE (`productid` = '36') and (`productname` = '유기농 재사용 커피필터\n') and (`price` = '4000');
UPDATE `fz_webapp`.`online_product` SET `img` = '3' WHERE (`productid` = '44') and (`productname` = '천연 설거지 수세미 (S/L)\n') and (`price` = '4000');
UPDATE `fz_webapp`.`online_product` SET `img` = '4' WHERE (`productid` = '38') and (`productname` = '다회용 밀랍 주방랩(M/L)\n') and (`price` = '4500');
UPDATE `fz_webapp`.`online_product` SET `img` = '5' WHERE (`productid` = '40') and (`productname` = '설거지용 팟 브러쉬\n') and (`price` = '6000');
UPDATE `fz_webapp`.`online_product` SET `img` = '6' WHERE (`productid` = '42') and (`productname` = '설거지용 롱핸들 브러쉬\n') and (`price` = '6500');
UPDATE `fz_webapp`.`online_product` SET `img` = '7' WHERE (`productid` = '35') and (`productname` = '유기농 설거지 비누(100g/400g)\n') and (`price` = '8000');
UPDATE `fz_webapp`.`online_product` SET `img` = '8' WHERE (`productid` = '106') and (`productname` = '친환경 제로웨이스트 주방용 다용도 천연 수세미\n') and (`price` = '800');
UPDATE `fz_webapp`.`online_product` SET `img` = '9' WHERE (`productid` = '112') and (`productname` = '[E,art] 천연 루파 수세미 열매') and (`price` = '3790');
UPDATE `fz_webapp`.`online_product` SET `img` = '10' WHERE (`productid` = '120') and (`productname` = '[E,art] 삼베 수세미') and (`price` = '3790');
UPDATE `fz_webapp`.`online_product` SET `img` = '11' WHERE (`productid` = '122') and (`productname` = '[E,art] 천연 루파 텀블러 세척솔') and (`price` = '4790');
UPDATE `fz_webapp`.`online_product` SET `img` = '12' WHERE (`productid` = '117') and (`productname` = 'E,art 디쉬바 옐루칼립투스') and (`price` = '5000');
UPDATE `fz_webapp`.`online_product` SET `img` = '13' WHERE (`productid` = '72') and (`productname` = '천연 물방울수세미\n') and (`price` = '3500');
UPDATE `fz_webapp`.`online_product` SET `img` = '14' WHERE (`productid` = '73') and (`productname` = '천연 통수세미\n') and (`price` = '3500');
UPDATE `fz_webapp`.`online_product` SET `img` = '15' WHERE (`productid` = '69') and (`productname` = '[손끋비] 밀랍랩(Small)\n') and (`price` = '5000');
UPDATE `fz_webapp`.`online_product` SET `img` = '16' WHERE (`productid` = '60') and (`productname` = '주방비누\n') and (`price` = '5200');
UPDATE `fz_webapp`.`online_product` SET `img` = '17' WHERE (`productid` = '61') and (`productname` = '[소렉스] 과일채소 세척솔\n') and (`price` = '6000');
UPDATE `fz_webapp`.`online_product` SET `img` = '18' WHERE (`productid` = '71') and (`productname` = '[레데커] 스크럽 세척솔\n') and (`price` = '6000');
UPDATE `fz_webapp`.`online_product` SET `img` = '19' WHERE (`productid` = '67') and (`productname` = '[예고은] 삼베찜시트\n') and (`price` = '6200');
UPDATE `fz_webapp`.`online_product` SET `img` = '20' WHERE (`productid` = '66') and (`productname` = '[손끋비] 밀랍랩(Large)\n') and (`price` = '7000');
UPDATE `fz_webapp`.`online_product` SET `img` = '21' WHERE (`productid` = '68') and (`productname` = '[소렉스] 팬용 세척솔\n') and (`price` = '7000');
UPDATE `fz_webapp`.`online_product` SET `img` = '22' WHERE (`productid` = '59') and (`productname` = '[예고은] 삼베수세미(3개입)\n') and (`price` = '8500');
UPDATE `fz_webapp`.`online_product` SET `img` = '23' WHERE (`productid` = '70') and (`productname` = '[손끋비] 밀랍랩 DIY세트(교육/체험용)\n') and (`price` = '9900');
UPDATE `fz_webapp`.`online_product` SET `img` = '24' WHERE (`productid` = '74') and (`productname` = '천연물방울수세미(3개입)\n') and (`price` = '9900');
UPDATE `fz_webapp`.`online_product` SET `img` = '25' WHERE (`productid` = '63') and (`productname` = '[손끋비] 밀랍랩 비기너세트(3매입)\n') and (`price` = '10000');
UPDATE `fz_webapp`.`online_product` SET `img` = '26' WHERE (`productid` = '64') and (`productname` = '[소렉스] 보틀 세척솔\n') and (`price` = '10000');
UPDATE `fz_webapp`.`online_product` SET `img` = '27' WHERE (`productid` = '65') and (`productname` = '[소렉스] 구리수세미 3pcs\n') and (`price` = '10000');

UPDATE `fz_webapp`.`online_product` SET `img` = '1' WHERE (`productid` = '1') and (`productname` = '제로웨이스트 입문 키트\n') and (`price` = '12000');
UPDATE `fz_webapp`.`online_product` SET `img` = '2' WHERE (`productid` = '58') and (`productname` = '제로웨이스트 구강위생 키트\n') and (`price` = '22000');
UPDATE `fz_webapp`.`online_product` SET `img` = '3' WHERE (`productid` = '131') and (`productname` = '100% 천연 밀랍초 비즈왁스 밀랍 캔들 3개 세트') and (`price` = '11000');
UPDATE `fz_webapp`.`online_product` SET `img` = '4' WHERE (`productid` = '123') and (`productname` = '[E,art] 먼지없는 강화 소창 2겹 행주 5장 세트') and (`price` = '12000');
UPDATE `fz_webapp`.`online_product` SET `img` = '5' WHERE (`productid` = '129') and (`productname` = 'E,art 프리미엄 집들이 선물 세트') and (`price` = '21300');
UPDATE `fz_webapp`.`online_product` SET `img` = '6' WHERE (`productid` = '100') and (`productname` = '[프리다]담금초 세트\n') and (`price` = '52000');

UPDATE `fz_webapp`.`online_product` SET `img` = '17' WHERE (`productid` = '101') and (`productname` = '[프리다]흐르는 작은 초\n') and (`price` = '22000');
UPDATE `fz_webapp`.`online_product` SET `img` = '16' WHERE (`productid` = '103') and (`productname` = '[프리다]코르크 밀랍초\n') and (`price` = '20000');
UPDATE `fz_webapp`.`online_product` SET `img` = '15' WHERE (`productid` = '94') and (`productname` = '[프리다]플로우 밀랍초\n') and (`price` = '10000');
UPDATE `fz_webapp`.`online_product` SET `img` = '14' WHERE (`productid` = '90') and (`productname` = '[소락] 유기농 면마스크\n') and (`price` = '6000');
UPDATE `fz_webapp`.`online_product` SET `img` = '13' WHERE (`productid` = '97') and (`productname` = '[프리다]노랑성냥\n') and (`price` = '4000');
UPDATE `fz_webapp`.`online_product` SET `img` = '12' WHERE (`productid` = '96') and (`productname` = '[프리다]꽈배기 생일초\n') and (`price` = '1100');
UPDATE `fz_webapp`.`online_product` SET `img` = '11' WHERE (`productid` = '95') and (`productname` = '[프리다]생일초\n') and (`price` = '1000');
UPDATE `fz_webapp`.`online_product` SET `img` = '10' WHERE (`productid` = '124') and (`productname` = 'E,art 린넨 롱 앞치마') and (`price` = '35800');
UPDATE `fz_webapp`.`online_product` SET `img` = '9' WHERE (`productid` = '128') and (`productname` = '[E,art] 심플리 하프 에이프런 2종') and (`price` = '18000');
UPDATE `fz_webapp`.`online_product` SET `img` = '8' WHERE (`productid` = '125') and (`productname` = 'E,art 골드 머그 1P') and (`price` = '12500');
UPDATE `fz_webapp`.`online_product` SET `img` = '7' WHERE (`productid` = '33') and (`productname` = '하누만 요가매트\n') and (`price` = '149000');
UPDATE `fz_webapp`.`online_product` SET `img` = '6' WHERE (`productid` = '12') and (`productname` = '팔로산토 우드스틱\n') and (`price` = '10000');
UPDATE `fz_webapp`.`online_product` SET `img` = '5' WHERE (`productid` = '16') and (`productname` = '유기농 순면생리대 누르Nur.\n') and (`price` = '6500');
UPDATE `fz_webapp`.`online_product` SET `img` = '4' WHERE (`productid` = '4') and (`productname` = '비누 틴케이스\n') and (`price` = '4500');
UPDATE `fz_webapp`.`online_product` SET `img` = '3' WHERE (`productid` = '27') and (`productname` = '대나무 연필깎이\n') and (`price` = '2000');
UPDATE `fz_webapp`.`online_product` SET `img` = '2' WHERE (`productid` = '10') and (`productname` = '신문지연필(5ea)\n') and (`price` = '2000');
UPDATE `fz_webapp`.`online_product` SET `img` = '1' WHERE (`productid` = '19') and (`productname` = '재생종이 볼펜\n') and (`price` = '1500');

/*
select * from online_product where big_category='etc' order by binary(big_category), binary(brand), price, productid;
*/